info/urls.py
from django.conf.urls import url
from django.contrib import admin
from info import views

urlpatterns = [
    url(r'^create/$', views.user_create, name='user_create'),
    url(r'^(?P<id>\d+)/$', views.user_detail, name='user_detail'),
    url(r'^$', views.user_list, name='user_list'),
    url(r'^(?P<id>\d+)/edit/$', views.user_edit, name='user_edit'),
    url(r'^(?P<id>\d+)/delete/$', views.user_delete, name='user_delete'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from info import views

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^', include("info.urls",namespace = "info")),
    #url(r'^info/', views.user_list, name='user_list'),
]

info/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.
class UserInfo(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email_id = models.EmailField(max_length=120)
    #dob = models.DateField(auto_now=False, auto_now_add = False)
    #contact = models.BigIntegerField()


    def __str__(self):
        return self.first_name

    def get_absolute_url(self):
        #return "/blogs/%s/" %(self.id)
        return reverse("info:user_detail", kwargs = {"id":self.id})

info/forms.py
from django import forms
from .models import UserInfo

class PostForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = [
            "first_name",
            "last_name",
            "email_id",
            #"contact",
            #"dob",
        ]

info/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from .models import UserInfo
from .forms import PostForm
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
def user_list(request):
    queryset = UserInfo.objects.all()
    context = {
    "object_list": queryset,
    "title": "User Information",
    }
    return render(request, "list.html", context)


def user_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit = False)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())
    context={
        "form":form,
    }
    return render(request, "form.html", context)


def user_edit(request,id=None):
    instance = get_object_or_404(UserInfo, id = id)
    form = PostForm(request.POST or None, instance = instance)
    if form.is_valid():
        instance = form.save(commit = False)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "title":instance.first_name,
        "instance" : instance,
        "form":form,
    }
    return render(request, "form.html", context)


def user_delete(request,id = None):
    instance = get_object_or_404(UserInfo, id = id)
    instance.delete()
    return redirect('info:user_list')


def user_detail(request, id):
    instance = get_object_or_404(UserInfo, id = id)
    context = {
        "title":"User Detail",
        "instance" : instance,
    }
    return render(request, "detail.html", context)

templates/detail.html
<html>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<head>
</head>
<body>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <div class='col-md-6 col-sm-offset-4'>
    <div class="page-header">
    <h1>Hello User!<small>Your details are:</small></h1>
    </div>
     <br/>
     <h2>
     First Name:{{ instance.first_name }} <br/>
     Last Name:{{instance.last_name}} <br/>
     Email id :{{instance.email_id}}<br/>
     </h2>
     <br/>
     <br/>
     <a href = "{% url 'info:user_list' %}">Back</a><vr/>
     <a href = "{% url 'info:user_edit' instance.id %}">Edit</a>
     <!--Contact No.:{{instance.contact}}<br/>
     Date Of Birth:{{instance.dob}}<br/>-->
    </div>
  </body>
</html>

templates/form.html
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h1> Please enter your details below.</h1>
  <form method="POST" action="">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit">
  </form>
  </body>
</html>

templates/list.html
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <h1>Users Information</h1>
    <table width="100%">
      <tr>
        <h3>
        <td>First Name</td>
        <td>Last Name</td>
        <td>Email id</td>
        <td>Actions</td>
        </h3>
      </tr>
    {% for each in object_list %}
      <tr>
        <td><a href="{{ each.get_absolute_url }}">{{each.first_name}}</td>
        <td>{{each.last_name}}</td>
        <td>{{each.email_id}}</td>
        <td>
          <a href="{% url 'info:user_edit' each.id %}">Edit</a>
          <a href="{% url 'info:user_delete' each.id %}">Delete</a>
        </td>
      </tr>
    {% endfor %}
  </body>
</html>